config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  devise_for :users
  resource :user, :only => :show do
    member { get :switch }
  end
  resources :groups do
    resources :memberships, :only => [:create, :destroy]
    resources :attachments
    resources :posts do
    	resources :comments, :only => [:create, :destroy]
    end
  end
  root to: 'visitors#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  mount_uploader :image, FileUploader
  mount_uploader :document, FileUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :posts, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :attachments, :dependent => :destroy

  after_create :assign_owner_as_member
  before_destroy :assign_another_group_to_owner

  def assign_owner_as_member
    user.membered_groups << self
    user.group = self
    user.save
  end

  def assign_another_group_to_owner
    user.group = user.membered_groups.where.not(:id => self.id).first
    user.save
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr :tag_list
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  belongs_to :group
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments

  has_many :taggings
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings,
  											:reject_if => :all_blank,
  											:allow_destroy => true
  accepts_nested_attributes_for :tags
  validates_presence_of :body, :title

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
	belongs_to :taggings

	has_many :taggings
	has_many :tags, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
	belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  extend FriendlyId
  friendly_id :name, use: :slugged

  def set_default_role
    self.role ||= :user
  end

  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :lockable, :timeoutable

  has_many :posts
  has_many :comments
  has_many :events
  has_many :attachments
  has_many :groups
  has_many :memberships
  has_many :membered_groups, :through => :memberships, :source => :group
  belongs_to :group # to show current dashboard

  before_save :set_default_group

  def set_default_group
    self.group ||= membered_groups.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_group
  before_filter :set_post

  def create
   @comment = @post.comments.create(comment_params.merge(:user => current_user))
   redirect_to [@group, @post], notice: "Comment successful."
  end

  def destroy
   @comment = @post.comments.where(id: params[:id], :user_id => current_user)
   @comment.destroy
   redirect_to [@group, @post], notice: "Comment deleted."
  end

  private

  def set_group
    @group = current_user.membered_groups.find(params[:group_id])
  end

  def set_post
    @post = @group.posts.friendly.find(params[:post_id])
  end

  def comment_params
   params.require(:comment).permit(:body)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    @groups = current_user.membered_groups.all
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = current_user.groups.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_user.groups.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:name, :photo, :description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_group
  before_action :set_post, only: [:show, :edit, :update, :destroy]

 def index
   @posts = @group.posts.page(params[:page]).per(5)
 end

 def show
   @post = @group.posts.friendly.find(params[:id])
   @comment = Comment.new
 end

 def new
   @post = current_user.posts.new
 end

 def edit
   @post = @group.posts.friendly.find(params[:id])
 end

 def create
   @post = @group.posts.new(post_params.merge(:user => current_user))
     if @post.save
       redirect_to [@group, @post], notice: 'Post was successfully created.'
     else
       render :new
     end
 end

 def update
   if @post.update(post_params)
     redirect_to [@group, @post], notice: 'Post was successfully updated.'
   else
     render :edit
   end
 end

 def destroy
   @post.destroy
   redirect_to group_posts_url(@group), notice: 'Post was successfully destroyed.'
 end

 private
   def set_post
     @post = @group.posts.friendly.find(params[:id])
   end

   def set_group
     @group = current_user.membered_groups.find(params[:group_id])
   end

   def post_params
     params.require(:post).permit(:title, :body, :image, :all_tags)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @group = current_user.group
  end

  def switch
    group = current_user.membered_groups.find(params[:group_id])
    current_user.update(:group => group)

    redirect_to user_path
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def group_nav_link(label, url, controller_name)
    # <li class="active"><%= link_to 'Dashboard', user_path(current_user) %></li>
    content_tag :li, :class => ('active' if controller.controller_name == controller_name) do
      link_to label, url
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="page-header">
  <h1>Listing Groups</h1>
</div>

<div class="row">
  <div class="col-md-10">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= group.name %></td>
            <td><%= group.description %></td>
            <% if group.user == current_user %>
              <td><%= link_to 'Show', group, :class => 'btn btn-primary btn-sm pull-left' %></td>
              <td><%= link_to 'Edit', edit_group_path(group), :class => 'btn btn-warning btn-sm pull-left' %></td>
              <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm pull-left' %></td>
            <% else %>
              <td colspan="3"></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Group', new_group_path, :class => 'btn btn-primary btn-sm pull-left'%>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="page-header">
  <h1>Showing Group: <%= @group.name %></h1>
</div>

<p>
  <h4>Group Description or Purpose: <%= @group.description %></h4>
</p>

<div class="page-header"></div>

<div class="row">
  <div class="col-md-8">
    <h2>Members of: <%= @group.name %></h2>
    <table class="table">
      <thead>
        <tr>
          <th>User</th>
          <th>Email</th>
          <th>Accepted?</th>
          <th>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @group.memberships.each do |membership| %>
          <% if membership.user != @group.user %>
            <tr>
              <td><%= membership.user.name %></td>
              <td><%= membership.user.email %></td>
              <td>
                <%= membership.user.invitation_accepted? ? 'Yes' : 'No' %>
              </td>
              <td><%= link_to 'Destroy', [@group, membership], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm pull-left' %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h3>Add/Invite User</h3>
    <%= simple_form_for([@group, Membership.new]) do |f| %>
      <%= f.error_notification %>
      <div class="form-group">
        <label>Name</label>
        <input name="name" type="text" class="form-control" placeholder="First Last">
      </div>
      <div class="form-group">
        <label>Email</label>
        <input name="email" type="email" class="form-control" placeholder="user@example.com">
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Invite" %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_group_path(@group), :class => 'btn btn-primary btn-sm pull-left' %> |
<%= link_to 'Back', groups_path, :class => 'btn btn-primary btn-sm pull-left' %>

app/views/posts/_form.html.erb
<%= form_for([@group, @post], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tag, "Tags (separated by commas)", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :all_tags, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', [@group, @post] %> |
<%= link_to 'Back', group_posts_path(@group) %>

app/views/posts/index.html.erb
<h1 class="page-header"><%= @group.name %>'s Posts</h1>
<%= link_to 'New Post', new_group_post_path(@group), :class => 'btn btn-primary btn-lg pull-left' %>

<div class="row"></div>

  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-sm-8 blog-main">
        <div class="blog-post">
          <h2 class="blog-post-title"><%= link_to(post.title, [@group, post]) %></h2>
          <p class="author">Submitted <%= time_ago_in_words(post.created_at) %> by <%= post.user.email %></p>
          <p class="blog-post-body"><%= post.body %></p>
          <p class="blog-post-tags">Tags: <%= post.all_tags %></p>
        </div>
      </div>
    </div>
  <% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', group_posts_path(@group) %>

app/views/posts/show.html.erb
<h1 class="page-header">Showing Post</h1>

    <div class="row">
      <div class="col-sm-8 blog-main">
        <div class="blog-post">
          <h2 class="blog-post-title"><%= @post.title %></h2>
          <p class="author">Submitted <%= time_ago_in_words(@post.created_at) %> by <%= @post.user.email %></p>
          <p class="blog-post-body"><%= @post.body %></p>
          <p class="blog-post-tags"><strong>Tags: </strong><%= @post.all_tags %></p>
        </div>
      </div>
    </div>

    <%= link_to 'Edit', edit_group_post_path(@group, @post), :class => 'btn btn-primary btn-sm pull-left' %>
    <%= link_to 'Back', group_posts_path(@group), :class => 'btn btn-primary btn-sm pull-left' %>


<div class="row"></div>
<div class="row">
  <div class="col-sm-8">
    <div class="blog-post">
      <h2>Comments</h2>
        <% @post.comments.each do |comment| %>
        	<dl class="dl-horizontal">
      	  	<dt>User:</dt>
      	  	<dd><%= comment.user.name %></dd>
      	  	<dt>Comment:</dt>
      	  	<dd><%= comment.body %></dd>
      		</dl>
        <% end %>
    </div>
    <div class="col-sm-8">
      <%= form_for([@group, @post, @comment]) do |f| %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
            <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.text_area :body %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>