config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  devise_for :users
  resource :user, :only => :show do
    member { get :switch }
  end
  resources :groups do
    resources :memberships, :only => [:create, :destroy]
    resources :attachments
    resources :posts do
    	resources :comments, :only => [:create, :destroy]
    end
  end
  root to: 'visitors#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  mount_uploader :image, FileUploader
  mount_uploader :document, FileUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :posts, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :attachments, :dependent => :destroy

  after_create :assign_owner_as_member
  before_destroy :assign_another_group_to_owner

  def assign_owner_as_member
    user.membered_groups << self
    user.group = self
    user.save
  end

  def assign_another_group_to_owner
    user.group = user.membered_groups.where.not(:id => self.id).first
    user.save
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr :tag_list
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  belongs_to :group
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments

  has_many :taggings
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings,
  											:reject_if => :all_blank,
  											:allow_destroy => true
  accepts_nested_attributes_for :tags
  validates_presence_of :body, :title

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
	belongs_to :taggings

	has_many :taggings
	has_many :tags, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
	belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  extend FriendlyId
  friendly_id :name, use: :slugged

  def set_default_role
    self.role ||= :user
  end

  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :lockable, :timeoutable

  has_many :posts
  has_many :comments
  has_many :events
  has_many :attachments
  has_many :groups
  has_many :memberships
  has_many :membered_groups, :through => :memberships, :source => :group
  belongs_to :group # to show current dashboard

  before_save :set_default_group

  def set_default_group
    self.group ||= membered_groups.first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    @groups = current_user.membered_groups.all
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = current_user.groups.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_user.groups.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:name, :photo, :description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_group
  before_action :set_post, only: [:show, :edit, :update, :destroy]

 def index
   @posts = @group.posts.page(params[:page]).per(5)
 end

 def show
   @post = @group.posts.friendly.find(params[:id])
   @comment = Comment.new
 end

 def new
   @post = current_user.posts.new
 end

 def edit
   @post = @group.posts.friendly.find(params[:id])
 end

 def create
   @post = @group.posts.new(post_params.merge(:user => current_user))
     if @post.save
       redirect_to [@group, @post], notice: 'Post was successfully created.'
     else
       render :new
     end
 end

 def update
   if @post.update(post_params)
     redirect_to [@group, @post], notice: 'Post was successfully updated.'
   else
     render :edit
   end
 end

 def destroy
   @post.destroy
   redirect_to group_posts_url(@group), notice: 'Post was successfully destroyed.'
 end

 private
   def set_post
     @post = @group.posts.friendly.find(params[:id])
   end

   def set_group
     @group = current_user.membered_groups.find(params[:group_id])
   end

   def post_params
     params.require(:post).permit(:title, :body, :image, :all_tags)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @group = current_user.group
  end

  def switch
    group = current_user.membered_groups.find(params[:group_id])
    current_user.update(:group => group)

    redirect_to user_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def group_nav_link(label, url, controller_name)
    # <li class="active"><%= link_to 'Dashboard', user_path(current_user) %></li>
    content_tag :li, :class => ('active' if controller.controller_name == controller_name) do
      link_to label, url
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to(image_tag('kidify_vector_small.png'), user_path, class: 'navbar-brand') %>
      <% else %>
        <%= link_to(image_tag('kidify_vector_small.png'), root_path, class: 'navbar-brand') %>
      <% end %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <% if user_signed_in? && current_user.group && current_user.membered_groups.size > 1 %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.group.name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <%- current_user.membered_groups.each do |group| %>
              <% if group != current_user.group %>
                <li><%= link_to group.name, switch_user_path(:group_id => group.id) %></li>
              <% end %>
            <%- end %>
          </ul>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Groups', groups_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    <% if current_user.try(:admin?) %>
      <li><%= link_to 'Admin', '/admin' %></li>
      <li><%= link_to 'Users', users_path %></li>
    <% end %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><%= content_for?(:title) ? yield(:title) : "Kidify" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Kidify" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="icon" href="../../favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <% if @group %>
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
              <%= render 'shared/group_navigation' %>
            </div>
            <div class="col-sm-9 col-md-10 main">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      <% else %>
        <%= render 'layouts/messages' %>
        <%= yield %>
      <% end %>
    </main>
    <footer>
      <p>Kelly Bristol for The Iron Yard 2015</p>
    </footer>
  </body>
</html>

app/views/mykidify/index.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-8 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h1 class="page-header">Kidify</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<header class="image-bg-fluid-height">
    <%= image_tag "newsplash.png" %>
</header>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>Kidify. The convenience of social media, with the security and peace of mind you deserve.</h3>
    <p>
    This Ruby on Rails application was created for
    <%= link_to('The Iron Yard', 'http://www.theironyard.com') %>
    by <%= link_to('Kelly Bristol', 'https://github.com/cateia97') %>.
    </p>
    <p>I came up with the concept for Kidify after watching my partner and his ex-wife struggle to coordinate schedules and various information for their 4-year-old autistic son. For a while, communication was practically non-existent. Keeping up-to-date with prescriptions, dietary changes, and therapy goals was a nightmare. They tried utilizing Google Drive and Google Calendar, but my partner quickly found that his contributions could be edited or even deleted.</p>
    <p>Initially, Kidify was intended to help separated parents co-parent more effectively. As I went through the initial concept phase, I reached out to my social media networks and found many parents (separated or not) were interested in using Kidify as a way to share milestones, photos, etc. with family without the hassle of larger social media networks (and their intrusive data collection policies). Other parents of children with special needs felt Kidify could satisfy a need to share information with teachers, daycare providers, and therapists without needing to exchange stacks of papers, which we all know become lost in a flash! With this feedback, Kidify has been designed with flexibility and security in mind. Use it how it works best for you! YOU control who gets access to your Kidify, and YOU choose what to upload.</p>
   </div>
  </div>

app/views/shared/_group_navigation.html.erb
<ul class="nav nav-sidebar">
  <%= group_nav_link "Dashboard", user_path, 'users' %>
  <% unless @group.new_record? %>
    <%= group_nav_link "Posts",  group_posts_path(@group), 'posts' %>
    <%= group_nav_link "Photos", group_attachments_path(@group), 'attachments' %>
    <li class="disabled"><a href="#">Documents</a></li>
    <li class="disabled"><a href="#">Calendar</a></li>
    <li class="disabled"><a href="#">Tasks</a></li>
  <% end %>
</ul>